name: HF integration tests

on:
  schedule:
    - cron:  '0 9 * * 0'  # every sunday at 9:00 UTC
  workflow_dispatch:

jobs:
  hf-integration-tests:

    runs-on: ubuntu-latest
    if: "github.repository == 'skorch-dev/skorch'"

    timeout-minutes: 10  # took 4 min during testing

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Requirements
      run: |
        python -m pip install -r requirements.txt
        python -m pip install torch -f https://download.pytorch.org/whl/torch_stable.html
        python -m pip install transformers tokenizers huggingface_hub
        python -m pip install .
    - name: run HF integration test
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python scripts/hf-integration-tests.py
